TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = win32-x86
ARCH = darwin-x86
TARGETS = envPaths
include $(TOP)/configure/RULES.ioc
TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = win32-x86
ARCH = darwin-x86
TARGETS = envPaths
include $(TOP)/configure/RULES.ioc
