TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

INC_WIN32 += tiff.h tiffio.h tiffvers.h tiffconf.h 

LIBRARY_IOC_WIN32 = tiff

LIB_SYS_LIBS_WIN32 += User32

LIB_SRCS += tif_aux.c
LIB_SRCS += tif_close.c
LIB_SRCS += tif_codec.c
LIB_SRCS += tif_color.c
LIB_SRCS += tif_compress.c
LIB_SRCS += tif_dir.c
LIB_SRCS += tif_dirinfo.c
LIB_SRCS += tif_dirread.c
LIB_SRCS += tif_dirwrite.c
LIB_SRCS += tif_dumpmode.c
LIB_SRCS += tif_error.c
LIB_SRCS += tif_extension.c
LIB_SRCS += tif_fax3.c
LIB_SRCS += tif_fax3sm.c
LIB_SRCS += tif_getimage.c
LIB_SRCS += tif_jbig.c
LIB_SRCS += tif_jpeg.c
LIB_SRCS += tif_jpeg_12.c
LIB_SRCS += tif_ojpeg.c
LIB_SRCS += tif_flush.c
LIB_SRCS += tif_luv.c
LIB_SRCS += tif_lzw.c
LIB_SRCS += tif_next.c
LIB_SRCS += tif_open.c
LIB_SRCS += tif_packbits.c
LIB_SRCS += tif_pixarlog.c
LIB_SRCS += tif_predict.c
LIB_SRCS += tif_print.c
LIB_SRCS += tif_read.c
LIB_SRCS += tif_stream.cpp
LIB_SRCS += tif_swab.c
LIB_SRCS += tif_strip.c
LIB_SRCS += tif_thunder.c
LIB_SRCS += tif_tile.c
LIB_SRCS += tif_version.c
LIB_SRCS += tif_warning.c
LIB_SRCS += tif_write.c
LIB_SRCS += tif_zip.c
LIB_SRCS += tif_win32.c
        
        
include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

