/* This file was automatically generated on Wed 22 Jan 2014 13:55:58 GMT from
 * source: /home/gnx91527/work/epics/hdf5_xml_layout/etc/makeIocs/hdf5LayoutXML.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

