TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = win32-x86
#ARCH = windows-x64
ARCH = linux-x86
#ARCH = solaris-sparc
#ARCH = vxWorks-ppc603
TARGETS = envPaths cdCommands
include $(TOP)/configure/RULES.ioc
