TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = win32-x86
#ARCH = windows-x64
#ARCH = windows-x64-debug
#ARCH = cygwin-x86
#ARCH = linux-x86
ARCH = linux-x86_64
#ARCH = solaris-sparc
#ARCH = vxWorks-ppc603
TARGETS = envPaths cdCommands dllPath.bat
include $(TOP)/configure/RULES.ioc
