TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

LIBRARY_IOC += ntndArrayConverter
INC += ntndArrayConverter.h
LIB_SRCS += ntndArrayConverter.cpp
USR_INCLUDES += -I$(EV4_BASE)/pvDataCPP/include
USR_INCLUDES += -I$(EV4_BASE)/normativeTypesCPP/include

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

