TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

INC_WIN32 += jpeglib.h jconfig.h jmorecfg.h jerror.h 

LIBRARY_IOC_WIN32 = jpeg

LIB_SRCS += jcapimin.c 
LIB_SRCS += jcapistd.c 
LIB_SRCS += jccoefct.c 
LIB_SRCS += jccolor.c
LIB_SRCS += jcdctmgr.c 
LIB_SRCS += jchuff.c 
LIB_SRCS += jcinit.c 
LIB_SRCS += jcmainct.c 
LIB_SRCS += jcmarker.c 
LIB_SRCS += jcmaster.c
LIB_SRCS += jcomapi.c 
LIB_SRCS += jcparam.c 
LIB_SRCS += jcphuff.c 
LIB_SRCS += jcprepct.c 
LIB_SRCS += jcsample.c 
LIB_SRCS += jctrans.c 
LIB_SRCS += jdapimin.c
LIB_SRCS += jdapistd.c 
LIB_SRCS += jdatadst.c 
LIB_SRCS += jdatasrc.c 
LIB_SRCS += jdcoefct.c 
LIB_SRCS += jdcolor.c
LIB_SRCS += jddctmgr.c 
LIB_SRCS += jdhuff.c 
LIB_SRCS += jdinput.c 
LIB_SRCS += jdmainct.c 
LIB_SRCS += jdmarker.c 
LIB_SRCS += jdmaster.c
LIB_SRCS += jdmerge.c 
LIB_SRCS += jdphuff.c 
LIB_SRCS += jdpostct.c 
LIB_SRCS += jdsample.c 
LIB_SRCS += jdtrans.c 
LIB_SRCS += jerror.c 
LIB_SRCS += jfdctflt.c
LIB_SRCS += jfdctfst.c 
LIB_SRCS += jfdctint.c
LIB_SRCS += jidctflt.c 
LIB_SRCS += jidctfst.c 
LIB_SRCS += jidctint.c 
LIB_SRCS += jidctred.c 
LIB_SRCS += jquant1.c
LIB_SRCS += jquant2.c 
LIB_SRCS += jutils.c 
LIB_SRCS += jmemmgr.c
LIB_SRCS += jmemnobs.c

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

